// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockAleoVerifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockAleoVerifier";
  readonly sourceName: "contracts/MockAleoVerifier.sol";
  readonly abi: [{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"DeprecatedContract","type":"error"}];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50604051633bab1f1360e11b815260040160405180910390fdfe";
  readonly deployedBytecode: "0x60806040525f80fdfea2646970667358221220606a60d882827726ac7ced0108cf3a1241c79be2c715bdb680c96795f40d3eab64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/MockAleoVerifier.sol";
  readonly buildInfoId: "solc-0_8_24-e17d0153754dfdfb6830aeca6d65f5e6568c4d9e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockAleoVerifier"]: MockAleoVerifier$Type;
    ["contracts/MockAleoVerifier.sol:MockAleoVerifier"]: MockAleoVerifier$Type;
  }
}